import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Poppins } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const poppins = Poppins({ subsets: ['latin'], weight: ["400", "500", "600"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='container'>
          <Navbar />
          {children}
          <Footer /></div>
      </body>
    </html>
  )
}
